---
# tasks file for roles/backup-config

- name: "check for required fact: backup_config"
  fail:
    msg: "Missing required fact: filename, path"
  when: not backup_config.filename or not backup_config.path 
 
- name: include device role specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - config_backup.yml
      paths:
        - "{{ playbook_dir }}/providers/{{ ansible_network_os }}"
        - "~/.ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "/etc/ansible/network/network-vlans/providers/{{ ansible_network_os }}"
        - "{{ role_path }}/providers/{{ ansible_network_os }}"
 

