---
# IOS provider for doing config backup
#
- name: Backup IOS config to specified location
  config_backup:
    path: "{{ backup_config.path }}"
    filename: "{{ backup_config.filename }}"
    backup: "{{ backup_config.backup }}"
    command: "show running-config"
